# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70d051f9c944e4194e4e838df96b2eab172201e717da8f0ef50b668d5d7d2dcce567a286a59d87f23ad61a8068d7e3d0cafe61d6a5da0713d36f434fb02fb464

test:
  secret_key_base: 6fbcd26da43bec147ccc6ef6d9edaaf0eda7b882d6ce96a4e268a3efcac1973e1339c0039bf88dd894129790cd97339d486fea2d44eccd3d5f3cc6f351b74469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
